### ISSUE TITLE
[Bug] Wrong Runtime if task failed

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork-web#11]
Hello, faced interesting issue:
```
state: RUNNING
createdAt: 2023-10-20T01:19:56.420301Z
scheduledAt: 2023-10-20T01:19:56.424951Z
startedAt: 2023-10-20T07:12:15.879177Z
failedAt: 2023-10-20T01:19:56.252516Z
```
![image](https://github.com/runabol/tork-web/assets/35843703/bce1ad5e-fd5f-4a07-88d3-771dca43c23a)

So, if task was failed we can see incorrect Runtime in `tork-web`

Will be nice to see some `Fail counter` near the task `State`

**Comment by ppcololo** [comment]
When it completed time is correct:
![image](https://github.com/runabol/tork-web/assets/35843703/0b7c42c1-c3d0-44b0-88f7-6570d76ed46a)

**Comment by runabol** [comment]
@ppcololo this should be fixed. could you confirm?

**Comment by ppcololo** [comment]
I don't know what did you fix, but I still see this issue:
![image](https://github.com/runabol/tork-web/assets/35843703/129b8a90-1eec-4bd7-92fb-41cbc342f430)

coordinator:
![image](https://github.com/runabol/tork-web/assets/35843703/e6b92f3c-07ad-404d-9569-473f7f9cc715)

**Comment by runabol** [comment]
Can you try again using the [latest release](https://github.com/runabol/tork/releases/tag/0.1.40)?

**Comment by ppcololo** [comment]
I will try, thanks.
But can't reproduce it right now.
If I have an issue then write here

**Comment by ppcololo** [comment]
![image](https://github.com/runabol/tork-web/assets/35843703/6765c5c2-d7b6-4efa-837e-981ffee39bac)

![image](https://github.com/runabol/tork-web/assets/35843703/723d121b-f790-4af9-884f-1bc8361c6db5)

```state: RUNNING
createdAt: 2023-11-11T04:32:06.689706Z
scheduledAt: 2023-11-11T04:32:06.700287Z
startedAt: 2023-11-11T05:37:18.931082Z
failedAt: 2023-11-11T04:32:06.675842Z```

**Comment by ppcololo** [comment]
New data: no time at all

![image](https://github.com/runabol/tork-web/assets/35843703/a67b6360-f7b0-4b84-b438-abc05463800e)

![image](https://github.com/runabol/tork-web/assets/35843703/317046f8-5a23-48c1-bf39-7d512b521aa3)

for running task
```
state: RUNNING
createdAt: 2023-11-15T11:46:35.067896Z
scheduledAt: 2023-11-15T11:46:35.091199Z
startedAt: 2023-11-15T11:46:35.214332Z
failedAt: 2023-11-15T11:46:35.0151Z
```

for completed
```
state: COMPLETED
createdAt: 2023-11-13T20:33:12.05211Z
scheduledAt: 2023-11-13T20:36:03.056434Z
startedAt: 2023-11-15T03:16:02.248571Z
completedAt: 2023-11-15T03:16:03.156508Z
```

**Comment by runabol** [comment]
Can you try again using the latest release?

**Comment by ppcololo** [comment]
I didn't see any issues
closing
