### ISSUE TITLE
DAG workflow

### ISSUE THREAD

**Issue by dreamCodeMan** [runabol/tork-web#12]
Add DAG workflow view, like https://github.com/dagu-dev/dag

**Comment by runabol** [comment]
The repo you references seems to be private or does not exist. I get a 404.

**Comment by dreamCodeMan** [comment]
I'm sorry, The correct link: https://github.com/dagu-dev/dagu

**Comment by runabol** [comment]
@dreamCodeMan neat UI. Not sure that it makes sense for Tork though as it's not a DAG-based workflow engine.
