### ISSUE TITLE
[Bug] After last updates can't match worker and Nodename

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork-web#13]
Hello
After last updates in the `Nodes` pages I can see `Name` and `Hostname` and for workers `Name` always = `Worker` - yes I don't want to name every Pod in Kubernetes.
But Inside Task I can see `nodeId: 40b03982c4354128a9a403b0d589935b` on which this task is running.
And if I want to see some logs and just check this worker I can't match `nodeId <> Nodename`.

Some time ago on `Nodes` page we could see this `nodeId`.
In this case I see 2 options:
1. rollback this `nodeId` to the `Nodes` page
2. instead of `nodeid` inside the task you have to use `Nodename` - because `nodeId` in this case absolutely useless

**Comment by ppcololo** [comment]
```
k -n tork exec -it tork-5948bbdf79-gdb4p -- cat config.toml
[broker]
type = "rabbitmq"

[broker.rabbitmq]
url = ""
consumer.timeout = "600m"

[worker]
name = ""

[worker.queues]
default = 1

[runtime]
type = "shell"

[runtime.shell]
cmd = ["/bin/sh", "-c"]
```
and
```
k -n tork exec -it tork-5948bbdf79-gdb4p -- env | grep TORK_WORKER
TORK_WORKER_NAME=$HOSTNAME
```
and this
![image](https://github.com/runabol/tork-web/assets/35843703/adff4ced-4ddf-4bac-ad12-e09e7eb98840)

**Comment by runabol** [comment]
Sorry, just re-read the issue and realized that the OP wants Tork's Node ID vs. the hostname (which is already there). 

I've added back the Node ID to the nodes page as I agree that it's useful to be able to correlate the task's node id to the nodes listing.

**Comment by ppcololo** [comment]
thanks, working.
