### ISSUE TITLE
Wrong time `started at` in Job for Tasks

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork-web#7]
When we create a Job and inside Tasks we have several time indicators:
```
createdAt: 
scheduledAt: 
startedAt: 
completedAt: 
```
But for all parallel tasks inside Job I see the same time `Started at` in the table (not inside task).
In another words: Inside Job view we can see the same time `Started at` for all tasks. 
But if we check some particular task we can see correct `startedAt` time - when this particular task started and this is not time when Job started

![image](https://github.com/runabol/tork-web/assets/35843703/e939629b-2ce8-411d-8dc2-77f15a9fa272)

**Comment by runabol** [comment]
Fixed by https://github.com/runabol/tork-web/pull/10
